spring.application.name=JobInsightSentry

# 1. ???? (????)
spring.profiles.active=dev
spring.thymeleaf.cache=false
server.port=8080

# 2. PostgreSQL ???????
# ????? docker-compose.yml ????
spring.datasource.url=jdbc:postgresql://localhost:5432/jobinsight
spring.datasource.username=user
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. JPA / Hibernate ??????
# update: ???????? Java Code ??????
spring.jpa.hibernate.ddl-auto=update
# ????????? SQL (??????)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect