spring.application.name=JobInsightSentry

# 1. ???? (????)//spring.profiles.active=prod
spring.profiles.active=prod
spring.thymeleaf.cache=false
server.port=8080

# 2. PostgreSQL ???????
# ????? docker-compose.yml ????
spring.datasource.url=jdbc:postgresql://localhost:5432/jobinsight
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. JPA / Hibernate ??????
# update: ???????? Java Code ??????
spring.jpa.hibernate.ddl-auto=update
# ????????? SQL (??????)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# LINE ??????
line.channel.token=${LINE_CHANNEL_ACCESS_TOKEN}
line.user.id=${line_user_id:}

# true ??????(production??), false ??????(dev??)
playwright.headless=false